spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: jdbc:postgresql://pg-29a3f253-haren-0320.i.aivencloud.com:24481/vibex_db
    username: 
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: true

minio:
  url: https://vibex96-vibex-storage.hf.space
  access-key: 
  secret-key: 
  buckets:
    playlist-images: playlist-images
    song-files: song-files
    user-avatars: user-avatars
    artist-files: artist-files
    album-files: album-files
