spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: jdbc:postgresql://host:port/vibex_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: true

minio:
  url: host-with-port-if
  access-key: minio-user
  secret-key: minio-pass
  buckets:
    playlist-images: playlist-images
    song-files: song-files
    user-avatars: user-avatars
